# Etapa 1: build
FROM node:20-alpine AS builder

WORKDIR /app

# Copia os arquivos do projeto
COPY package*.json ./
COPY tsconfig*.json ./
COPY . .

# Instala as dependências
RUN npm install

# Compila o projeto
RUN npm run build

# Etapa 2: imagem final
FROM node:20-alpine

WORKDIR /app

# Copia apenas o que é necessário da imagem de build
COPY --from=builder /app/package*.json ./
COPY --from=builder /app/dist/src ./dist
COPY --from=builder /app/node_modules ./node_modules

# Expõe a porta (ajuste se necessário)
EXPOSE 3000

# Comando para iniciar a aplicação
CMD ["node", "dist/main.js"]